# Generated by Django 5.1.6 on 2025-06-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0002_proposal_delete_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='client_email',
        ),
    ]
