# Generated by Django 5.1.6 on 2025-06-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0003_remove_proposal_client_email'),
        ('client_app', '0009_staff_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='lead',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='client_app.lead'),
            preserve_default=False,
        ),
    ]
