# Generated by Django 5.1.6 on 2025-06-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0004_proposal_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='file',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='description',
        ),
        migrations.AddField(
            model_name='proposal',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
