# Generated by Django 5.1.6 on 2025-07-18 11:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pipeline', '0001_initial'),
        ('client_app', '0016_card_lead'),
        ('myapp', '0013_client_fcm_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='pincode',
            new_name='postalcode',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='board',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='tag',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='companyname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tags',
            field=models.ManyToManyField(blank=True, to='client_app.tag'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='title',
            field=models.CharField(default='2025-07-18 17:05:00', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_leads', to='client_app.column'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lead_images/'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
