# Generated by Django 5.1.6 on 2025-06-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estimate', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
