# Generated by Django 5.1.6 on 2025-06-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estimate', '0004_delete_product'),
        ('client_app', '0009_staff_fcm_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('lead', 'estimate_number')},
        ),
    ]
