# Generated by Django 5.1.6 on 2025-06-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimate', '0005_alter_estimate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_number',
            field=models.CharField(max_length=50),
        ),
    ]
