# Generated by Django 5.1.6 on 2025-04-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0002_staff_created_at_staff_role_alter_staff_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('Staff', 'Staff')], default='Staff', max_length=100),
        ),
    ]
