# Generated by Django 5.1.6 on 2025-04-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
