# Generated by Django 5.1.6 on 2025-04-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leads',
        ),
        migrations.DeleteModel(
            name='Reseller',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
