# Generated by Django 5.1.6 on 2025-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_is_reseller_customuser_is_staff_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
