# Generated by Django 5.1.6 on 2025-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_customuser_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
