# Generated by Django 5.1.6 on 2025-05-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_newboard_leadcolumn_newboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='newboard',
            name='template',
            field=models.CharField(default='blue', max_length=100),
        ),
    ]
