# Generated by Django 5.1.6 on 2025-05-05 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_board_remove_leadcolumn_newboard_column_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='client_app.newboard'),
        ),
    ]
