# Generated by Django 5.1.6 on 2025-06-01 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_tag_lead_tags'),
        ('communications', '0003_qrtoken_delete_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.operator'),
        ),
    ]
