# Generated by Django 5.1.6 on 2025-06-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_lead_assigned_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
