# Generated by Django 5.1.6 on 2025-07-11 07:22

from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field



class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_staff_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_details',
            field=CKEditor5Field(blank=True, null=True),
        ),
    ]
