# Generated by Django 5.1.6 on 2025-07-11 07:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_alter_lead_lead_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lead_details',
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
    ]
