# Generated by Django 5.1.6 on 2025-07-11 08:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_remove_lead_lead_details_lead_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
