# Generated by Django 5.1.6 on 2025-07-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_alter_lead_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
