# Generated by Django 5.1.6 on 2025-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0014_add_description_to_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='board_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='column_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
