# Generated by Django 5.1.6 on 2025-07-17 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0015_lead_board_id_lead_column_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.lead'),
        ),
    ]
