# Generated by Django 5.1.6 on 2025-06-20 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.category'),
        ),
    ]
