# Generated by Django 5.1.6 on 2025-06-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_course_duration_remove_course_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
