# Generated by Django 5.1.6 on 2025-06-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_digitalproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
