# Generated by Django 5.1.6 on 2025-06-23 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_digitalcategory_physicalcategory_servicecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.physicalcategory'),
        ),
    ]
